# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildWithMaven
  displayName: 'Build with Maven'
  steps:
  - task: UseJavaVersion@0
    inputs:
      versionSpec: '11'  # Use the version of Java required by your project
    displayName: 'Set up Java'

  - task: Maven@3
    inputs:
      mavenPomFile: 'path/to/pom.xml'  # Adjust this path based on your project structure
      goals: 'clean install'
      options: '-Xmx3072m'  # Optional: Adjust the heap size if needed
    displayName: 'Build with Maven'
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
